name:                my-example-haskell-lib
version:             0.1.0.0
github:              "githubuser/my-example-haskell-lib"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
  - README.md

description:         Please see the README on GitHub at <https://github.com/githubuser/my-example-haskell-lib#readme>

dependencies:
  - base >= 4.7 && < 5

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
    - conduit
    - lens
    - servant
    - servant-cassava
    - servant-client
    - servant-server

tests:
  my-example-haskell-lib-test:
    main: Spec.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    source-dirs: test
    dependencies:
      - hspec
      - my-example-haskell-lib
